### Problem Statement:

Edureka has hired 1000 new employees, the HR has contacted you, and provided you with a text file having new employees’ names. He wants you to help him with generating Employees IDs, Emails, and Password

### Tasks to be performed:

1. Hey buddy, we have hired 1000 new employees. Here are the names in a text file, each name is separated using a new line. Can you generate the following:
    - Employee ID: Starting from 2020001. Example 2020001, 2020002 and so on 
    - Email ID: first_name.last_name@edureka.co 
    - Password: It should be an alphanumeric value, must having capital letters, small letters, and special symbols 
2. I need you to perform some operations on the data, so can we load the data in a Pandas DataFrame
3. Just to cross-check, can you show me the first 2 and the last 3 rows. Also, let’s check the shape of the DataFrame and print the data-types of each column 
4. Print the employee id, email id, and password of ‘Nancy Zediker’
5. Can we check if the column ‘Email ID’, it should not contain any duplicate emails, also check its size and print the first 10 values
    - If duplicate email is found, add a number in the duplicated email We have planned to invite them on lunch in batches. 
6. Lets create the first batch of all people whose names are starting with ‘A’. Also give me their count
7. I just got to know, that the people at index 10, 130, and 560 will not be joining so please remove their record 
8. We also need to share the data with the finance department so can you create a new DataFrame without the password column and save it in an excel file for sharing 
9. Can you tell me how I will access the data from excel file using names. For example show me the data for 'John Brown’ and 'Michael Combes’

### Download the text file containing name

In [4]:
!wget https://www.dropbox.com/s/onl5ac2ea3v11aw/names.txt --no-check-certificate

SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2021-05-28 18:05:57--  https://www.dropbox.com/s/onl5ac2ea3v11aw/names.txt
Resolving www.dropbox.com... 162.125.81.18, 2620:100:6031:18::a27d:5112
Connecting to www.dropbox.com|162.125.81.18|:443... connected.
WARNING: cannot verify www.dropbox.com's certificate, issued by `/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/onl5ac2ea3v11aw/names.txt [following]
--2021-05-28 18:05:58--  https://www.dropbox.com/s/raw/onl5ac2ea3v11aw/names.txt
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc45ab29dcc7d20fae90a2e37857.dl.dropboxusercontent.com/cd/0/inline/BPXZ9AnYc-4kSrMgwoMtkTKPdr6gCEvPN-moW0ZzWbDUKhqTDRYoQIkkxuW63WAZnNBfBRn5tk-DolQPUi6EnUgxLfYtoGarcoITND9F2aBLYf_pP65FDhXhZ_fBSYdlXaIMtb-p38peuemR8KaKXRPf/file# [following]
--2021-05-28 18:05:58--  https://uc45ab29dcc7d20fae90a2e37857.dl.dropboxusercontent.com/cd/0/inline/BPXZ9AnYc-4kSrMgwoMtkTKPdr6gCEvPN-moW0ZzWbDUKhqTDRYoQIkkxuW63WAZnNBfBRn5tk-DolQPUi6EnUgxLfYtoGarcoITND9F2aBLYf_pP65FDhXhZ_fBSYdlXaIMtb-p38peuemR8KaKXRPf/file
Resolving uc45ab29dcc7d20fae90a2e37857.dl.dropboxusercontent.com... 162.125.81.15, 2620:100:6031:15::a27d:510f
Connecting to uc45ab29dcc7d20fae90a2e37857.dl.dropboxusercontent.com|162.125.81.15|:443... connected.
WARNING: cannot verify uc45ab29dcc7d20fae90a2e37857.dl.dropboxusercontent.com's certificate, issued by `/C=US/O=DigiCert Inc/CN=DigiCert TLS RSA SHA256 2020 CA1':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 14024 (14K) [text/plain]
Saving to: `file'

     0K .......... ...                                        100%  324M=0s

2021-05-28 18:05:59 (324 MB/s) - `file' saved [14024/14024]

### Task 1: Read names and create empId, emailId & password for each name

Read the names, In the text file each name is separated using a new line. 
Can you generate the following: 
* Employee ID: Starting from 2020001. Example 2020001, 2020002 … 
* Email ID: first_name.last_name@edureka.co 
* Password: It should be alphanumeric value, must having capital letters, small letters, and special symbols

In [ ]:
file1 = open('/content/names.txt','r')
names = file1.read()
file1.close()

In [ ]:
names = names.strip().split('\n') #strip() is used to remove space around the string.  split() is splitting the string using '\n'
print(names[:10])
len(names)

['Edward Davis', 'John Brown', 'Cristopher Mccrate', 'Michael Combes', 'Jeff Blount', 'Joseph Ferris', 'Pablo Bruner', 'Ronnie Waite', 'Edward Gonzalez', 'Ruby Musetti']

1000

In [ ]:
#importing the required libraries
import pandas as pd
import random
import numpy as np

In [ ]:
sp_symbol = ['#','$','@','?', '&', '!']
def pass_gen():
    #function to generate password
    pwd = []
    caps_alpha = [chr(random.randrange(65, 65+26)) for _ in range(random.randrange(1, 4))]
    small_alpha = [chr(random.randrange(97, 97+26)) for _ in range(random.randrange(3, 6))]
    np.random.shuffle(sp_symbol)
    pwd.append(sp_symbol[0])
    num = [str(random.randrange(0,10)) for _ in range(random.randrange(1, 4)) ]
    pwd = pwd + caps_alpha + small_alpha + num
    np.random.shuffle(pwd)
    pwd = ''.join(pwd)
    return pwd

In [ ]:
print(pass_gen()) #test password generator function

rPwvl5@1

In [ ]:
def email_gen(name):
    name = name.split()
    email = '.'.join(name)
    return email.lower()+'@edureka.co'

In [ ]:
print(email_gen('Abhishek Singh'))

abhishek.singh@edureka.co

In [ ]:
emp_id = [id for id in range(2020001,2020001+1000)]
email = [ email_gen(name) for name in names ]
password = [pass_gen() for _ in range(1000)]

### Task 2: Create a pandas DataFrame

- First column should contain names
- Second column should contain Employee ID
- Third column should contain Email ID
- Fourth column should contain Password

In [ ]:
df = pd.DataFrame({'Name':names,'Employee ID': emp_id,'Email ID':email, 'Password': password})

#### Other ways to create a dataframe

In [ ]:
#creating a dataframe from multi-dimensional array
x = np.array([[90,95,100],[98,100,99]])
df = pd.DataFrame(x)
print(df)
print('type:',type(df))

In [ ]:
#creating a dataframe from a list of dictionaries
x = [{'Abhi':90,'Ankit':95,'Atul':100},{'Abhi':98,'Atul':99,'Ankit':100}]
df = pd.DataFrame(x,index = ['Maths','Physics'])
print(df)

### Task 3: Print the first 2 and last 3 rows, print the shape, print the data-types of each column

In [ ]:
df.head(2) #by default it will print 5 lines

           Name  Employee ID                 Email ID    Password
0  Edward Davis      2020001  edward.davis@edureka.co  Rxo8!t9OQ0
1    John Brown      2020002    john.brown@edureka.co    la4BBk$0

In [ ]:
df.tail(3)

                 Name  Employee ID                     Email ID   Password
997  Jeanette Sandlin      2020998  jeanette.sandlin@edureka.co   Xbm@o7CD
998     Nancy Zediker      2020999     nancy.zediker@edureka.co  a12uPxcg$
999    Edward Richter      2021000    edward.richter@edureka.co   4!4d7rNu

In [ ]:
print('type: ',type(df))
print('shape of the dataframe:',df.shape)
df.dtypes

type:  <class 'pandas.core.frame.DataFrame'>
shape of the dataframe: (1000, 4)

Name           object
Employee ID     int64
Email ID       object
Password       object
dtype: object

shape (1000 , 4) means 1000 rows and 4 columns

### Task 4: Print the employee id, email id, and password of 'Nancy Zediker'

In [ ]:
df[df['Name']=='Nancy Zediker'] #fetching data from the dataframe for the name Nancy Zediker

              Name  Employee ID                  Email ID   Password
998  Nancy Zediker      2020999  nancy.zediker@edureka.co  a12uPxcg$

### Task 5: Working with pandas Series object

* Select the column 'Email ID'
* Check the size of the column and print its first 10 values
* Check for duplicate emails
* If duplicate emails add a number to the next number

In [ ]:
print(df['Email ID'].head()) #selecting a column
print('type: ',type(df['Email ID'])) # A column is a pandas Series
print('Size of the column:',df['Email ID'].size)
print(df['Email ID'].values[:10]) #returns the list of values from the series

0          edward.davis@edureka.co
1            john.brown@edureka.co
2    cristopher.mccrate@edureka.co
3        michael.combes@edureka.co
4           jeff.blount@edureka.co
Name: Email ID, dtype: object
type:  <class 'pandas.core.series.Series'>
Size of the column: 1000
['edward.davis@edureka.co' 'john.brown@edureka.co'
 'cristopher.mccrate@edureka.co' 'michael.combes@edureka.co'
 'jeff.blount@edureka.co' 'joseph.ferris@edureka.co'
 'pablo.bruner@edureka.co' 'ronnie.waite@edureka.co'
 'edward.gonzalez@edureka.co' 'ruby.musetti@edureka.co']

In [ ]:
#duplicated method of pandas series can be used to find duplicate values in the Series
df['Email ID'].duplicated() #returns a boolean

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: Email ID, Length: 1000, dtype: bool

In [ ]:
df['Email ID'].duplicated().any() #any() method returns True if there are one or more True

True

We can see there are some duplicate values

In [ ]:
#Finding the duplicate value except the first occurence
df[df['Email ID'].duplicated()]  #Boolean Indexing

              Name  Employee ID                  Email ID   Password
850  Lois Thompson      2020851  lois.thompson@edureka.co  7R4fn@ng7

In [ ]:
df[df['Name']=='Lois Thompson'] #Checking where else Lois Thompson is occuring

              Name  Employee ID                  Email ID    Password
598  Lois Thompson      2020599  lois.thompson@edureka.co  @hsII5Ta5v
850  Lois Thompson      2020851  lois.thompson@edureka.co   7R4fn@ng7

In [ ]:
df.loc[850,'Email ID'] = 'lois.thompson2.edureka.co'

In [ ]:
df.iloc[850]

Name                       Lois Thompson
Employee ID                      2020851
Email ID       lois.thompson2.edureka.co
Password                       7R4fn@ng7
Name: 850, dtype: object

### Task 6: Find all the employees whose name starts with 'A'
Also print the total number of names starting with 'A'

In [ ]:
#Names starting with 'A'
x = df[df['Name'].str.startswith('A')] #boolean indexing
print(x.head())
print("The total number of names starting with 'A' are:",x.size) #total number of names starting with 'A'

               Name  Employee ID                   Email ID     Password
23       Alfredo Yu      2020024      alfredo.yu@edureka.co   9ql?I5N5eV
68   Ashley Nettles      2020069  ashley.nettles@edureka.co  Qs!ufeB29mF
77     Alice Vallee      2020078    alice.vallee@edureka.co   a7&7vRqFv0
96   Adrienne Huber      2020097  adrienne.huber@edureka.co  e1Av8$kFsbY
113     Ahmad Olson      2020114     ahmad.olson@edureka.co    yFh!sp0lI
The total number of names starting with 'A' are: 248

### Task 7: Remove the details of those people who are not going to join. They are at 10,130,560

In [ ]:
df.iloc[[10,130,560]]

               Name  Employee ID                   Email ID      Password
10      Della Janek      2020011     della.janek@edureka.co       !qqf9AY
130  William Ponyah      2020131  william.ponyah@edureka.co  8hyUd4zcK$N2
560  Joseph Brussel      2020561  joseph.brussel@edureka.co      !bdJEF0g

In [ ]:
df.drop([10,130,560],inplace=True) #inplace=True means make the change in-place, dont return a new dataframe
#drop() method is used to delete rows and columns, by default axis = 0, which means delete row-wise

In [ ]:
df.shape

(997, 4)

We can see 3 people's data has been removed

### Task 8: Also create a new dataframe without password column and save it in an excel file

In [ ]:
public_df = df.drop('Password',axis=1) #Deletes the column ‘Password’, axis=1 represents delete the column, by default axis is 0 meaning row deletion
public_df.head()

                 Name  Employee ID                       Email ID
0        Edward Davis      2020001        edward.davis@edureka.co
1          John Brown      2020002          john.brown@edureka.co
2  Cristopher Mccrate      2020003  cristopher.mccrate@edureka.co
3      Michael Combes      2020004      michael.combes@edureka.co
4         Jeff Blount      2020005         jeff.blount@edureka.co

### Task 9: Save the dataframe in an excel file

In [ ]:
public_df.to_excel('public_emp_data.xlsx',index=False)
df.to_excel('emp_id.xlsx',index=False)

### Task 10: Read the excel file in a dataframe with names as indexes

In [ ]:
data = pd.read_excel('/content/emp_id.xlsx',index_col='Name')

In [ ]:
data.head()

                    Employee ID                       Email ID    Password
Name
Edward Davis            2020001        edward.davis@edureka.co  Rxo8!t9OQ0
John Brown              2020002          john.brown@edureka.co    la4BBk$0
Cristopher Mccrate      2020003  cristopher.mccrate@edureka.co    s$5Pa96z
Michael Combes          2020004      michael.combes@edureka.co   kRj9zf0$d
Jeff Blount             2020005         jeff.blount@edureka.co  fEGoy7$Pex

Select rows using index labels

In [ ]:
print(data.loc['John Brown']) #Selecting rows using label
data.loc[['John Brown','Michael Combes']]

Employee ID                  2020002
Email ID       john.brown@edureka.co
Password                    la4BBk$0
Name: John Brown, dtype: object

                Employee ID                   Email ID   Password
Name
John Brown          2020002      john.brown@edureka.co   la4BBk$0
Michael Combes      2020004  michael.combes@edureka.co  kRj9zf0$d

### Additional task: Generating a list of 1000 names and writing it in a file

In [ ]:
'''
!pip install names
import names
'''

'\n!pip install names\nimport names\n'

In [ ]:
#names = [names.get_full_name() for _ in range(1000)]

In [ ]:
'''
file1 = open('names.txt','w')
for n in names:
  file1.write(n+'\n')
file1.close()
'''

"\nfile1 = open('names.txt','w')\nfor n in names:\n  file1.write(n+'\n')\nfile1.close()\n"

### Other Pandas Functionalities

#### Demo: Analysis of the titanic dataset
Dataset columns:

- survival:	Survival
- pclass:	Ticket class
- sex:	Sex
- Age:	Age in years
- sibsp:	Number of siblings / spouses aboard the Titanic	
- parch:	Number of parents / children aboard the Titanic	
- ticket:	Ticket number	
- fare:	Passenger fare	
- cabin:	Cabin number
- embarked:	Port of Embarkation

In [3]:
!wget https://www.dropbox.com/s/yrv9cj3kcpopjxh/train.csv --no-check-certificate #downloading titanic dataset

SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2021-05-28 18:04:36--  https://www.dropbox.com/s/yrv9cj3kcpopjxh/train.csv
Resolving www.dropbox.com... 162.125.81.18, 2620:100:6031:18::a27d:5112
Connecting to www.dropbox.com|162.125.81.18|:443... connected.
WARNING: cannot verify www.dropbox.com's certificate, issued by `/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/yrv9cj3kcpopjxh/train.csv [following]
--2021-05-28 18:04:37--  https://www.dropbox.com/s/raw/yrv9cj3kcpopjxh/train.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 404 Not Found
2021-05-28 18:04:37 ERROR 404: Not Found.

http://#downloading: Invalid host name.
--2021-05-28 18:04:37--  http://titanic/
Resolving titanic... failed: Host not found.
wget: unable to resolve host address `titanic'
--2021-05-28 18:04:40--  http://dataset/
Resolving dataset... failed: Host not found.
wget: unable to resolve host address `dataset'

In [ ]:
# read a csv file
# You can read different type of files in pandas DataFrame like,
#  read_excel(), read_json(), read_html(), read_sql(), read_pickle()
import pandas as pd
df = pd.read_csv('/content/train.csv')
df.head() #display first 5 rows

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
print(df['Survived'].value_counts()) #value_counts() method returns the frequency of each value
df['Sex'].unique() #returns the unique values in the dataset

0    549
1    342
Name: Survived, dtype: int64

array(['male', 'female'], dtype=object)

In [ ]:

df['Survived'] #Selecting a column
df[['Survived','Pclass','Age']] #Selecting multiple columns

     Survived  Pclass   Age
0           0       3  22.0
1           1       1  38.0
2           1       3  26.0
3           1       1  35.0
4           0       3  35.0
..        ...     ...   ...
886         0       2  27.0
887         1       1  19.0
888         0       3   NaN
889         1       1  26.0
890         0       3  32.0

[891 rows x 3 columns]

In [ ]:
#Creating a new column
df['normalized_fare'] = df['Fare']/100
df.head(2)

   PassengerId  Survived  Pclass  ... Cabin Embarked  normalized_fare
0            1         0       3  ...   NaN        S         0.072500
1            2         1       1  ...   C85        C         0.712833

[2 rows x 13 columns]

In [ ]:
df.dtypes #data-types of each column

PassengerId          int64
Survived             int64
Pclass               int64
Name                object
Sex                 object
Age                float64
SibSp                int64
Parch                int64
Ticket              object
Fare               float64
Cabin               object
Embarked            object
normalized_fare    float64
dtype: object

In [ ]:
df.info() #Printing the info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PassengerId      891 non-null    int64
 1   Survived         891 non-null    int64
 2   Pclass           891 non-null    int64
 3   Name             891 non-null    object
 4   Sex              891 non-null    object
 5   Age              714 non-null    float64
 6   SibSp            891 non-null    int64
 7   Parch            891 non-null    int64
 8   Ticket           891 non-null    object
 9   Fare             891 non-null    float64
 10  Cabin            204 non-null    object
 11  Embarked         889 non-null    object
 12  normalized_fare  891 non-null    float64
dtypes: float64(3), int64(5), object(5)
memory usage: 90.6+ KB

In [ ]:
import numpy as np
#Selecting columns with mentioned data-types
num_df = df.select_dtypes(include=[np.number])
num_df.head()

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  normalized_fare
0            1         0       3  22.0      1      0   7.2500         0.072500
1            2         1       1  38.0      1      0  71.2833         0.712833
2            3         1       3  26.0      0      0   7.9250         0.079250
3            4         1       1  35.0      1      0  53.1000         0.531000
4            5         0       3  35.0      0      0   8.0500         0.080500

###**Exploring Descriptive Analytics**

In [ ]:
df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [ ]:
print('The average age of all passengers',df['Age'].mean())
print('The standard deviation of column "Age" of all passengers',df['Age'].std())

The average age of all passengers 29.69911764705882
The standard deviation of column "Age" of all passengers 14.526497332334044

In [ ]:
df.describe()

       PassengerId    Survived  ...        Fare  normalized_fare
count   891.000000  891.000000  ...  891.000000       891.000000
mean    446.000000    0.383838  ...   32.204208         0.322042
std     257.353842    0.486592  ...   49.693429         0.496934
min       1.000000    0.000000  ...    0.000000         0.000000
25%     223.500000    0.000000  ...    7.910400         0.079104
50%     446.000000    0.000000  ...   14.454200         0.144542
75%     668.500000    1.000000  ...   31.000000         0.310000
max     891.000000    1.000000  ...  512.329200         5.123292

[8 rows x 8 columns]

In [ ]:
 #correlation among different features
df.corr()

                 PassengerId  Survived  ...      Fare  normalized_fare
PassengerId         1.000000 -0.005007  ...  0.012658         0.012658
Survived           -0.005007  1.000000  ...  0.257307         0.257307
Pclass             -0.035144 -0.338481  ... -0.549500        -0.549500
Age                 0.036847 -0.077221  ...  0.096067         0.096067
SibSp              -0.057527 -0.035322  ...  0.159651         0.159651
Parch              -0.001652  0.081629  ...  0.216225         0.216225
Fare                0.012658  0.257307  ...  1.000000         1.000000
normalized_fare     0.012658  0.257307  ...  1.000000         1.000000

[8 rows x 8 columns]

You can see 'Fare' column is highly correlated with 'Survived' feature