### Problem Statement:

Edureka has hired 1000 new employees, the HR has contacted you, and provided you with a text file having new employees’ names. He wants you to help him with generating Employees IDs, Emails, and Password

### Tasks to be performed:

1. Hey buddy, we have hired 1000 new employees. Here are the names in a text file, each name is separated using a new line. Can you generate the following:
    - Employee ID: Starting from 2020001. Example 2020001, 2020002 and so on
    - Email ID: first_name.last_name@edureka.co
    - Password: It should be an alphanumeric value, must having capital letters, small letters, and special symbols
2. I need you to perform some operations on the data, so can we load the data in a Pandas DataFrame
3. Just to cross-check, can you show me the first 2 and the last 3 rows. Also, let’s check the shape of the DataFrame and print the data-types of each column
4. Print the employee id, email id, and password of ‘Nancy Zediker’
5. Can we check if the column ‘Email ID’, it should not contain any duplicate emails, also check its size and print the first 10 values
    - If duplicate email is found, add a number in the duplicated email We have planned to invite them on lunch in batches.
6. Lets create the first batch of all people whose names are starting with ‘A’. Also give me their count
7. I just got to know, that the people at index 10, 130, and 560 will not be joining so please remove their record
8. We also need to share the data with the finance department so can you create a new DataFrame without the password column and save it in an excel file for sharing
9. Can you tell me how I will access the data from excel file using names. For example show me the data for 'John Brown’ and 'Michael Combes’

### Download the text file containing name

In [ ]:
# !wget https://www.dropbox.com/s/onl5ac2ea3v11aw/names.txt --no-check-certificate
!wget https://www.dropbox.com/s/onl5ac2ea3v11aw/names.txt

### Task 1: Read names and create empId, emailId & password for each name

Read the names, In the text file each name is separated using a new line.
Can you generate the following:
* Employee ID: Starting from 2020001. Example 2020001, 2020002 …
* Email ID: first_name.last_name@edureka.co
* Password: It should be alphanumeric value, must having capital letters, small letters, and special symbols

In [ ]:
file1 = open('/content/names.txt','r')
names = file1.read()
file1.close()

In [ ]:
names = names.strip().split('\n') #strip() is used to remove space around the string.  split() is splitting the string using '\n'
print(names[:10])
len(names)

In [ ]:
#importing the required libraries
import pandas as pd
import random
import numpy as np

In [ ]:
sp_symbol = ['#','$','@','?', '&', '!']
def pass_gen():
    #function to generate password
    pwd = []
    caps_alpha = [chr(random.randrange(65, 65+26)) for _ in range(random.randrange(1, 4))]
    small_alpha = [chr(random.randrange(97, 97+26)) for _ in range(random.randrange(3, 6))]
    np.random.shuffle(sp_symbol)
    pwd.append(sp_symbol[0])
    num = [str(random.randrange(0,10)) for _ in range(random.randrange(1, 4)) ]
    pwd = pwd + caps_alpha + small_alpha + num
    np.random.shuffle(pwd)
    pwd = ''.join(pwd)
    return pwd

In [ ]:
print(pass_gen()) #test password generator function

In [ ]:
def email_gen(name):
    name = name.split()
    email = '.'.join(name)
    return email.lower()+'@edureka.co'

In [ ]:
print(email_gen('Abhishek Singh'))

In [ ]:
emp_id = [id for id in range(2020001,2020001+1000)]
email = [ email_gen(name) for name in names ]
password = [pass_gen() for _ in range(1000)]

### Task 2: Create a pandas DataFrame

- First column should contain names
- Second column should contain Employee ID
- Third column should contain Email ID
- Fourth column should contain Password

In [ ]:
df = pd.DataFrame({'Name':names,'Employee ID': emp_id,'Email ID':email, 'Password': password})
print(df.shape)
df.head()

#### Other ways to create a dataframe

In [ ]:
#creating a dataframe from multi-dimensional array
x = np.array([[90,95,100],[98,100,99]])
df = pd.DataFrame(x, columns=['a','b','c'], index=['r1', 'r2'])
# df = pd.DataFrame(x)
# print(df)
print('type:',type(df))
df

In [ ]:
#creating a dataframe from a list of dictionaries
x = [{'Abhi':90,'Ankit':95,'Atul':100},{'Abhi':98,'Atul':99,'Ankit':100}]
df = pd.DataFrame(x,index = ['Maths','Physics'])
# df = pd.DataFrame(x)
df

### Task 3: Print the first 2 and last 3 rows, print the shape, print the data-types of each column

In [20]:
df = pd.DataFrame({'Name':names,'Employee ID': emp_id,'Email ID':email, 'Password': password})
print(df.shape)
df.head()

(1000, 4)

,Name,Employee ID,Email ID,Password
0,Edward Davis,2020001,edward.davis@edureka.co,U!Wt5kfUm
1,John Brown,2020002,john.brown@edureka.co,9pJA@Nq8e9
2,Cristopher Mccrate,2020003,cristopher.mccrate@edureka.co,4O0aIu#qe
3,Michael Combes,2020004,michael.combes@edureka.co,4aCayb3Cg&1Z
4,Jeff Blount,2020005,jeff.blount@edureka.co,b7wlpv3T$B

In [21]:
df.head(2) #by default it will print 5 lines

           Name  Employee ID                 Email ID    Password
0  Edward Davis      2020001  edward.davis@edureka.co   U!Wt5kfUm
1    John Brown      2020002    john.brown@edureka.co  9pJA@Nq8e9

In [22]:
df.tail(3)

                 Name  Employee ID                     Email ID     Password
997  Jeanette Sandlin      2020998  jeanette.sandlin@edureka.co  L?6fiq0zKpJ
998     Nancy Zediker      2020999     nancy.zediker@edureka.co    Ohduu2!JR
999    Edward Richter      2021000    edward.richter@edureka.co  a05eBp@llHF

In [ ]:
print('type: ',type(df))
print('shape of the dataframe:',df.shape)
df.dtypes

shape (1000 , 4) means 1000 rows and 4 columns

### Task 4: Print the employee id, email id, and password of 'Nancy Zediker'

In [28]:
# print(type(df['Name']))
# df['Name'].head()

In [29]:
# df['Name']=='Nancy Zediker'

In [30]:
df[df['Name']=='Nancy Zediker'] #fetching data from the dataframe for the name Nancy Zediker

              Name  Employee ID                  Email ID   Password
998  Nancy Zediker      2020999  nancy.zediker@edureka.co  Ohduu2!JR

### Task 5: Working with pandas Series object

* Select the column 'Email ID'
* Check the size of the column and print its first 10 values
* Check for duplicate emails
* If duplicate emails add a number to the next number

In [ ]:
# dfsmall = df.head(10)
# print(dfsmall.shape)
# dfsmall

In [34]:
df['Email ID'].head()

0          edward.davis@edureka.co
1            john.brown@edureka.co
2    cristopher.mccrate@edureka.co
3        michael.combes@edureka.co
4           jeff.blount@edureka.co
Name: Email ID, dtype: object

In [33]:
print(df['Email ID'].head()) #selecting a column
print('type: ',type(df['Email ID'])) # A column is a pandas Series
print('Size of the column:',df['Email ID'].size)
print(df['Email ID'].values[:10]) #returns the list of values from the series

0          edward.davis@edureka.co
1            john.brown@edureka.co
2    cristopher.mccrate@edureka.co
3        michael.combes@edureka.co
4           jeff.blount@edureka.co
Name: Email ID, dtype: object
type:  <class 'pandas.core.series.Series'>
Size of the column: 1000
['edward.davis@edureka.co' 'john.brown@edureka.co'
 'cristopher.mccrate@edureka.co' 'michael.combes@edureka.co'
 'jeff.blount@edureka.co' 'joseph.ferris@edureka.co'
 'pablo.bruner@edureka.co' 'ronnie.waite@edureka.co'
 'edward.gonzalez@edureka.co' 'ruby.musetti@edureka.co']

In [35]:
#duplicated method of pandas series can be used to find duplicate values in the Series
df['Email ID'].duplicated() #returns a boolean

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: Email ID, Length: 1000, dtype: bool

In [36]:
df['Email ID'].duplicated().any() #any() method returns True if there are one or more True

True

We can see there are some duplicate values

In [37]:
#Finding the duplicate value except the first occurence
df[df['Email ID'].duplicated()]  #Boolean Indexing

              Name  Employee ID                  Email ID  Password
850  Lois Thompson      2020851  lois.thompson@edureka.co  5h@8urKV

In [38]:
df[df['Name']=='Lois Thompson'] #Checking where else Lois Thompson is occuring

              Name  Employee ID                  Email ID     Password
598  Lois Thompson      2020599  lois.thompson@edureka.co  eYX66nOfo?8
850  Lois Thompson      2020851  lois.thompson@edureka.co     5h@8urKV

In [39]:
df.loc[850, 'Email ID']

'lois.thompson@edureka.co'

In [40]:
df.iloc[850,2]

'lois.thompson@edureka.co'

In [41]:
df.loc[850,'Email ID'] = 'lois.thompson2@edureka.co'

In [42]:
df[df['Name']=='Lois Thompson']

              Name  Employee ID                   Email ID     Password
598  Lois Thompson      2020599   lois.thompson@edureka.co  eYX66nOfo?8
850  Lois Thompson      2020851  lois.thompson2@edureka.co     5h@8urKV

### Task 6: Find all the employees whose name starts with 'A'
Also print the total number of names starting with 'A'

In [43]:
df.dtypes

Name           object
Employee ID     int64
Email ID       object
Password       object
dtype: object

In [45]:
#Names starting with 'A'
x = df[df['Name'].str.startswith('A')] #boolean indexing

print("The total number of names starting with 'A' are:",x.size) #total number of names starting with 'A'
x.head()

The total number of names starting with 'A' are: 248

               Name  Employee ID                   Email ID    Password
23       Alfredo Yu      2020024      alfredo.yu@edureka.co    e0n&Nvnr
68   Ashley Nettles      2020069  ashley.nettles@edureka.co   k!enGV0sU
77     Alice Vallee      2020078    alice.vallee@edureka.co   am7Kn7A3#
96   Adrienne Huber      2020097  adrienne.huber@edureka.co  hbh97D6me?
113     Ahmad Olson      2020114     ahmad.olson@edureka.co  Qc#l25Lv7K

### Task 7: Remove the details of those people who are not going to join. They are at 10,130,560

In [46]:
df.iloc[[10,130,560]]

               Name  Employee ID                   Email ID     Password
10      Della Janek      2020011     della.janek@edureka.co  T1lYhxo4a1$
130  William Ponyah      2020131  william.ponyah@edureka.co    x2kN&xp8K
560  Joseph Brussel      2020561  joseph.brussel@edureka.co    ndn3c5zC!

In [47]:
df.drop([10,130,560],inplace=True) #inplace=True means make the change in-place, dont return a new dataframe
#drop() method is used to delete rows and columns, by default axis = 0, which means delete row-wise

In [48]:
df.shape

(997, 4)

We can see 3 people's data has been removed

### Task 8: Also create a new dataframe without password column and save it in an excel file

In [49]:
public_df = df.drop('Password',axis=1) #Deletes the column ‘Password’, axis=1 represents delete the column, by default axis is 0 meaning row deletion
public_df.head()

                 Name  Employee ID                       Email ID
0        Edward Davis      2020001        edward.davis@edureka.co
1          John Brown      2020002          john.brown@edureka.co
2  Cristopher Mccrate      2020003  cristopher.mccrate@edureka.co
3      Michael Combes      2020004      michael.combes@edureka.co
4         Jeff Blount      2020005         jeff.blount@edureka.co

In [50]:
df.head()

,Name,Employee ID,Email ID,Password
0,Edward Davis,2020001,edward.davis@edureka.co,U!Wt5kfUm
1,John Brown,2020002,john.brown@edureka.co,9pJA@Nq8e9
2,Cristopher Mccrate,2020003,cristopher.mccrate@edureka.co,4O0aIu#qe
3,Michael Combes,2020004,michael.combes@edureka.co,4aCayb3Cg&1Z
4,Jeff Blount,2020005,jeff.blount@edureka.co,b7wlpv3T$B

### Task 9: Save the dataframe in an excel file

In [52]:
public_df.to_excel('public_emp_data.xlsx',index=False)
df.to_excel('emp_id.xlsx',index=False)

In [54]:
public_df.to_csv('public_emp_data.csv',index=False)

### Task 10: Read the excel file in a dataframe with names as indexes

In [55]:
data1 = pd.read_excel('/content/emp_id.xlsx',index_col='Name')
data2 = pd.read_csv('/content/public_emp_data.csv')

In [56]:
data1.head()

                    Employee ID                       Email ID      Password
Name
Edward Davis            2020001        edward.davis@edureka.co     U!Wt5kfUm
John Brown              2020002          john.brown@edureka.co    9pJA@Nq8e9
Cristopher Mccrate      2020003  cristopher.mccrate@edureka.co     4O0aIu#qe
Michael Combes          2020004      michael.combes@edureka.co  4aCayb3Cg&1Z
Jeff Blount             2020005         jeff.blount@edureka.co    b7wlpv3T$B

In [58]:
data1.shape

(997, 3)

In [57]:
data2.head()

                 Name  Employee ID                       Email ID
0        Edward Davis      2020001        edward.davis@edureka.co
1          John Brown      2020002          john.brown@edureka.co
2  Cristopher Mccrate      2020003  cristopher.mccrate@edureka.co
3      Michael Combes      2020004      michael.combes@edureka.co
4         Jeff Blount      2020005         jeff.blount@edureka.co

Select rows using index labels

In [59]:
print(data1.loc['John Brown']) #Selecting rows using label
data1.loc[['John Brown','Michael Combes']]

Employee ID                  2020002
Email ID       john.brown@edureka.co
Password                  9pJA@Nq8e9
Name: John Brown, dtype: object

                Employee ID                   Email ID      Password
Name
John Brown          2020002      john.brown@edureka.co    9pJA@Nq8e9
Michael Combes      2020004  michael.combes@edureka.co  4aCayb3Cg&1Z

### Additional task: Generating a list of 1000 names and writing it in a file

In [ ]:
'''
!pip install names
import names
'''

In [ ]:
#names = [names.get_full_name() for _ in range(1000)]

In [ ]:
'''
file1 = open('names.txt','w')
for n in names:
  file1.write(n+'\n')
file1.close()
'''

### Other Pandas Functionalities

#### Demo: Analysis of the titanic dataset
Dataset columns:

- survival:	Survival
- pclass:	Ticket class
- sex:	Sex
- Age:	Age in years
- sibsp:	Number of siblings / spouses aboard the Titanic
- parch:	Number of parents / children aboard the Titanic
- ticket:	Ticket number
- fare:	Passenger fare
- cabin:	Cabin number
- embarked:	Port of Embarkation

In [ ]:
!wget https://www.dropbox.com/s/yrv9cj3kcpopjxh/train.csv --no-check-certificate #downloading titanic dataset

In [ ]:
# read a csv file
# You can read different type of files in pandas DataFrame like,
#  read_excel(), read_json(), read_html(), read_sql(), read_pickle()
import pandas as pd
df = pd.read_csv('/content/train.csv')
df.head() #display first 5 rows

In [ ]:
print(df['Survived'].value_counts()) #value_counts() method returns the frequency of each value
df['Sex'].unique() #returns the unique values in the dataset

In [ ]:

df['Survived'] #Selecting a column
df[['Survived','Pclass','Age']] #Selecting multiple columns

In [ ]:
#Creating a new column
df['normalized_fare'] = df['Fare']/100
df.head(2)

In [ ]:
df.dtypes #data-types of each column

In [ ]:
df.info() #Printing the info

In [ ]:
import numpy as np
#Selecting columns with mentioned data-types
num_df = df.select_dtypes(include=[np.number])
num_df.head()

###**Exploring Descriptive Analytics**

In [ ]:
df['Sex'].value_counts()

In [ ]:
print('The average age of all passengers',df['Age'].mean())
print('The standard deviation of column "Age" of all passengers',df['Age'].std())

In [ ]:
df.describe()

In [ ]:
 #correlation among different features
df.corr()

You can see 'Fare' column is highly correlated with 'Survived' feature